services:
  postgres-db:
    image: postgres:latest
    container_name: local-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: local-dynamodb
    ports:
      - "8000:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb"
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal

#  backend-app:
#    build: .
#    container_name: local-backend
#    ports:
#      - "8080:8080"
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/ssp
#      - SPRING_DATASOURCE_USERNAME=admin
#      - SPRING_DATASOURCE_PASSWORD=admin
#      - AWS_DYNAMODB_ENDPOINT=http://dynamodb-local:8000
#      - AWS_ACCESS_KEY_ID=DUMMYIDEXAMPLE
#      - AWS_SECRET_ACCESS_KEY=DUMMYEXAMPLEKEY
#      - REGION=us-east-1
#    depends_on:
#      - postgres-db
#      - dynamodb-local

volumes:
  postgres_data:
