spring.datasource.url=${DB_URL_PROD}
spring.datasource.username=${DB_USERNAME_PROD}
spring.datasource.password=${DB_PASSWORD_PROD}

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.connection-timeout=30000

logging.level.root=INFO

spring.graphql.graphiql.enabled=false
spring.jpa.show-sql=false
